** Do we really think anymore?
I makes me wonder if we really think these days. I remember my school
days, the time that I have had to think and do nothing else.  Now,
those moments of solitude seems like a thing of the past. The times
when new ideas came in during potty times. Now even that tiny bit of
time has be taken by personal gadgets. These gadgets stream in
information and never let you imagine or think about stuff.  When was
the last time did I wonder why something works the way it does. We
always are quick enough to grab the gadget and look it up online.

Thinking does not have to produce new ideas all the time. What about
pondering over something that we come across during our commute to
work?  If everything was available in the books and no one had to
think anything then how did humans manage to create the online world,
which is devoid of physical books.  Tools were created during the
stone age. In what frequency were new tools being built at that point
in time only time_travel can tell. I hope we were thinking a lot at
that time. Thinking on how to bring down our hunt and how to stay
alive from potential predators. Then we chose to write(or draw). This
was one art that humans could have started without any spectators. In
the stone age, if I could write, I bet only I could read it. So that
must have been the first encrypted document (until the other person
learns what it meant). We were good thinkers.

With times changing we invented more and more tools - more
imagination - more thinking - more products. With all the ages passing
by, we remained creative because we thought that we could do something
more. In the information age, when you think you wanted to do
something, you look up online to see if it already exists. This is the
beginning of death of the first thought.  Even if what you thought
already exists, you could think about how you would do it rather than
going through the checklist of features that you want to be on the
product. Had you thought more about it, the outcome could have been
different. A thinking mind is unpredictable. The probability that your
outcome would have been at least slightly different had you tried your
mind in thinking and conceiving that idea. It all begins with
conception isn't it? 

At first it was the thought, then word, then action. Should we not
engage ourselves effectively in the first part. Think about it.

